### ISSUE TITLE
关于在训练阶段的问题

### ISSUE THREAD

**Issue by wangnaihao** [chenmc1996/Robust-LR#1]
您好！非常有幸拜读您的工作！我有一个小小的疑问，就是每次在train阶段I设置成2，相当于训练两次，这样做对于提升性能有什么帮助，谢谢，期待您的答复！

**Comment by chenmc1996** [comment]
您好，感谢您的关注。在经过I个epoch训练后，我们会切换到另一个模型训练，可以理解为控制两个模型同步频率的超参数。当这个超参数I的值越大时，单个模型在另一个模型更新之前更新的次数就会越多，因此频率越低。
